name:                crypto-fr
version:             0.1.0.0
github:              "githubuser/crypto-fr"
license:             BSD3
author:              "Matthew Collins"
maintainer:          "collins.t.matthew@protonmail.com"
copyright:           "2020 Matthew Collins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/crypto-fr#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  crypto-fr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-fr
    - sqlite-simple
tests:
  crypto-fr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-fr
